### ISSUE TITLE
Recommended way to load all available extensions?

### ISSUE THREAD

**Issue by richardeakin** [mosra/flextgl#16]
Hi,

I'm getting familiar with flextgl here, sorry if this obvious - is there a recommended way to load all available extensions in the profile.txt file, or template? We'd like to use flextgl with our framework where we don't know just what extensions users may need, so it'd be nice to request them all as optional in our case. I believe this is how GLEW and glLoadGen work as well (though they are in a separate header in those loaders).

**Comment by mosra** [comment]
Hi,

Generally from my past experience with GL, having *all extensions* was not desirable: some extensions conflicted with each other, some in the XML file were experimental, marked as "do not use" etc. 

As far as I know, both GLEW and glLoadGen have a dedicated builtin list of "common extensions", so I propose maintaining something like that here as well. What target you need? GL, GLES2, GLES3 or Vulkan?

**Comment by richardeakin** [comment]
Oh, I didn't realize that. I would think that a blacklist could work around some of those conflicts, but I'm really not sure nor do I have much experience with gl extension loaders. I think your solution could work as a default way to load common extensions as GLEW and glLoadGen do.

We're looking to replace glLoadGen in our framework (libcinder), which we currently use for OpenGL only. Probably will be looking to use it for GLES2/3 as well but not in the immediate.

Though, would be fairly easy to generate the extensions list? I'm wondering if this is the process one way or another, if we should just do it on our end to create the profile.txt file.

**Comment by mosra** [comment]
I think blacklist would not be enough, even. And after that you end up with basically exactly the same what GLEW is doing, having huge headers that load everything and a ton of patches on top of that. At that point you could just use GLEW, in my opinion.

With GL it's also about core and compatibility profile, and based on which you want to support, you either need to load *tons* of extensions or just some of them. I don't think the users need *everything*, loading latest GL 4.6 + a bunch of very common extensions on top might be sufficient.

[Here are lists that glLoadGen was using](https://bitbucket.org/alfonse/glloadgen/src/e48321572bf6c2cbbac310a52c4071471005e425/extfiles/?at=default), so I bet your generated headers used one of these? Isn't exactly a lot, tho.

[This is what I am using in Magnum](https://github.com/mosra/magnum/blob/master/src/MagnumExternal/OpenGL/GL/extensions.txt), basically pulling in all extensions that are core in GL 4.6 (*almost* all ARB extensions are in) plus a bunch of common extensions that are not in core yet. This relatively short list corresponds to this quite long list [in the Magnum documentation](http://doc.magnum.graphics/magnum/opengl-support.html). If you go one level up in the repository, you'll find also the ES2/ES3 and corresponding WebGL1/WebGL2 extension lists.

**Comment by mosra** [comment]
Closing as resolved, suggested solution is to maintain a list of all extensions or base it off an existing one from the links above.
